name: asoscijacije_nove
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 3.0.0+22

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
  
    sdk: flutter


  
  animations: ^2.0.7
  animated_text_kit: ^4.2.2
  build_runner: ^2.4.5
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  flutter_card_swiper: ^6.0.0
  flutter_form_builder: ^9.0.0
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  in_app_update: ^4.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  just_audio: ^0.9.34
  page_transition: ^2.0.9
  riverpod: ^2.3.6
  device_preview: ^1.1.0
  flutter_svg: ^2.0.9

flutter_native_splash:
  color: "#17113D"
  image: "assets/images/image_splash.png"
  branding: "assets/images/branding_splash.png"
  android_12: 
    color: "#17113D"
    image: "assets/images/image_splash.png"
    fill: true
    branding: "assets/images/branding_splash.png"
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/sounds/correct-choice.mp3
    - assets/images/

  fonts:
    - family: Geologica
      fonts:
        - asset: assets/fonts/Geologica-Regular.ttf
        - asset: assets/fonts/Geologica-Thin.ttf
          weight: 100
        - asset: assets/fonts/Geologica-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Geologica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geologica-Black.ttf
          weight: 900
  
